import { PublicKey } from '@solana/web3.js';

export const RELAYER_BASE_URL = 'https://relayer.umbraprivacy.com/';
export const INDEXER_BASE_URL = 'https://5nqw12m1pa.execute-api.eu-central-1.amazonaws.com/proof/';
export const MERKLE_TREE_DEPTH = 48;

export const NULLIFIER_HASH_PDA_SEED = Buffer.from('nullifier_hash:');
export const USER_ALLOTED_COMPLIANCE_GRANT_PDA_SEED = Buffer.from('user_alloted_compliance_grant:');

export const WSOL_MINT_ADDRESS = new PublicKey('So11111111111111111111111111111111111111112');

export const ARCIUM_ENCRYPTED_USER_ACCOUNT_FLAG_BIT_FOR_IS_INITIALISED = 0;
export const ARCIUM_ENCRYPTED_USER_ACCOUNT_FLAG_BIT_FOR_IS_MXE_ENCRYPTED = 1;
export const ARCIUM_ENCRYPTED_USER_ACCOUNT_FOR_HAS_REGISTERED_MASTER_VIEWING_KEY = 2;
export const ARCIUM_ENCRYPTED_USER_ACCOUNT_FLAG_BIT_FOR_IS_ACTIVE = 3;
export const ARCIUM_ENCRYPTED_USER_ACCOUNT_FLAG_BIT_FOR_REQUIRES_SOL_DEPOSIT = 4;

export const ARCIUM_ENCRYPTED_TOKEN_ACCOUNT_FLAG_BIT_FOR_IS_INITIALISED = 0;
export const ARCIUM_ENCRYPTED_TOKEN_ACCOUNT_FLAG_BIT_FOR_IS_ACTIVE = 1;
export const ARCIUM_ENCRYPTED_TOKEN_ACCOUNT_FLAG_BIT_FOR_IS_ARCIUM_BALANCE_INITIALISED = 2;
export const ARCIUM_ENCRYPTED_TOKEN_ACCOUNT_FLAG_BIT_FOR_IS_MXE_ENCRYPTED = 3;
